# Config file for automatic testing at travis-ci.org

arch:
    - arm64
    - amd64
language: python

python:
  - 3.6

install: pip install pytest

# command to run tests, e.g. python setup.py test
script: py.test
sudo: false
